import { Course, Institute } from './lib/supabase';

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    titel: 'Instrumentalstudium Viola',
    slug: 'instrumentalstudium-viola',
    beschreibung_generiert: 'Ein umfassendes Studium für Viola-Spieler auf höchstem Niveau.',
    kategorie: 'Musik',
    institut_id: '1',
    institut_name: 'Fachhochschule Technikum Wien',
    regelstudienzeit: '8 Semester',
    standort: 'Wien',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.400',
    kosten_jahr: '€ 600',
    kosten_monat: '€ 50',
    studienform: 'Vollzeit',
    plaetze: '15',
    sprache: 'Deutsch',
    studienbeginn: 'Oktober 2026',
    website_url: 'https://www.technikum-wien.at',
    image_url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '17',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '18',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
  {
    id: '19',
    titel: 'International Business Management',
    slug: 'international-business-management',
    beschreibung_generiert: 'Bereiten Sie sich auf eine globale Karriere im Management vor.',
    kategorie: 'Wirtschaft',
    institut_id: '2',
    institut_name: 'FH Kufstein Tirol',
    regelstudienzeit: '6 Semester',
    standort: 'Kufstein',
    abschluss: 'Bachelor of Arts',
    ects: '180',
    gesamtkosten: '€ 2.178',
    kosten_jahr: '€ 726',
    kosten_monat: '€ 60,50',
    studienform: 'Berufsbegleitend',
    plaetze: '30',
    sprache: 'Englisch/Deutsch',
    studienbeginn: 'September 2026',
    website_url: 'https://www.fh-kufstein.ac.at',
    image_url: 'https://images.unsplash.com/photo-1454165833767-027ff33027ef?auto=format&fit=crop&q=80&w=800',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_INSTITUTES: Institute[] = [
  {
    id: '1',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Fachhochschule Technikum Wien',
    slug: 'fh-technikum-wien',
    beschreibung: 'Österreichs größte rein technische Fachhochschule.',
    adresse: 'Höchstädtplatz 6, 1200 Wien',
    location: 'Wien',
    logo: 'https://www.technikum-wien.at/wp-content/themes/fhtw/assets/img/logo.svg',
    website: 'https://www.technikum-wien.at',
    facebook: 'https://facebook.com/technikumwien',
    instagram: 'https://instagram.com/technikumwien',
    youtube: 'https://youtube.com/technikumwien',
    created_at: new Date().toISOString(),
  },
];
